ARRAY PICTURE:C279(PAGES;0)
<>PP:=->PAGES

ARRAY TEXT:C222(PAGENO;0)
<>PN:=->PAGENO

C_PICTURE:C286(PAGE)
CLEAR VARIABLE:C89(PAGE)

<>PI:=->PAGE

CLEAR VARIABLE:C89(CODE)

$p:=New process:C317("Method1";0;"$PDF2SVG")