/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Poppler.h
 #	source generated by 4D Plugin Wizard
 #	Project : Poppler
 #	author : miyako
 #	2021/04/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_POPPLER_H
#define PLUGIN_POPPLER_H

#include "4DPluginAPI.h"

#include <assert.h>
#include <stdlib.h>
#include <glib.h>
#include <poppler.h>
#include <poppler-document.h>
#include <poppler-page.h>
#include <cairo.h>
#include <cairo-svg.h>
#include <stdio.h>
#include <string.h>

#include "C_BLOB.h"
#include "C_LONGINT.h"
#include "ARRAY_TEXT.h"

typedef PA_long32 method_id_t;

#if VERSIONMAC
#import <Cocoa/Cocoa.h>
#endif

typedef enum{
 PDF2SVG_ReturnNothing = 0,
 PDF2SVG_ReturnPicture = 1,
 PDF2SVG_ReturnText = 2,
 PDF2SVG_ReturnBlob = 3
}PDF2SVG_ReturnType;

#define PDF2SVG_ERROR_InvalidSourceData (-1)
#define PDF2SVG_ERROR_InvalidReturnType (-2)
#define PDF2SVG_ERROR_AbortedByUser (-3)

#pragma mark -

void PDF_Convert(PA_PluginParameters params);
void PDF_Get_page_count(PA_PluginParameters params);
void PDF_Get_text(PA_PluginParameters params);

#endif /* PLUGIN_POPPLER_H */
